# Generated by Django 4.1.2 on 2022-11-15 10:14

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='проверка мобильного телефона', regex='^7\\w{10}$')], verbose_name='Мобильный телефон')),
                ('operator_code', models.CharField(max_length=3, verbose_name='Код оператора клиента')),
                ('tag', models.CharField(max_length=20, verbose_name='Тег')),
                ('timezone', models.IntegerField(verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField(verbose_name='Дата и время начала рассылки')),
                ('stop_dt', models.DateTimeField(verbose_name='Дата и время окончания рассылки')),
                ('text', models.CharField(max_length=100, verbose_name='Текст рассылки')),
                ('filtr', models.CharField(choices=[('Оператор', 'Оператор'), ('Тег', 'Тег')], max_length=32)),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Отправлено', 'Отправлено'), ('Не отправлено', 'Не отправлено')], default='Не отправлено', max_length=15, verbose_name='статус сообщения')),
                ('send_dt', models.DateTimeField(default=datetime.datetime(2022, 11, 15, 10, 14, 58, 214347), verbose_name='Дата и время отправки')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_sender.client', verbose_name='ИД клиента')),
                ('dispatch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_sender.dispatch', verbose_name='ИД рассылки')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
