# Generated by Django 4.1.2 on 2022-11-15 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_sender', '0002_alter_message_send_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_dt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 10, 21, 15, 485744, tzinfo=datetime.timezone.utc), verbose_name='Дата и время отправки'),
        ),
    ]
