# Generated by Django 4.1.2 on 2022-11-15 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_sender', '0003_alter_message_send_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='timezone',
            field=models.IntegerField(verbose_name='Часовой пояс GMT+'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='filtr',
            field=models.CharField(choices=[('Оператор', 'Оператор'), ('Тег', 'Тег')], max_length=32, verbose_name='Фильтр'),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_dt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 10, 48, 48, 117957, tzinfo=datetime.timezone.utc), verbose_name='Дата и время отправки'),
        ),
    ]
