# Generated by Django 4.1.2 on 2022-11-15 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_sender', '0005_alter_client_operator_code_alter_dispatch_filtr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Оператор',
                'verbose_name_plural': 'Операторы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='tag',
            field=models.CharField(max_length=15, verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_dt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 14, 38, 28, 331921, tzinfo=datetime.timezone.utc), verbose_name='Дата и время отправки'),
        ),
    ]
