# Generated by Django 4.1.2 on 2022-11-15 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_sender', '0007_alter_message_send_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='code',
        ),
        migrations.AlterField(
            model_name='message',
            name='send_dt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 14, 53, 13, 286285, tzinfo=datetime.timezone.utc), verbose_name='Дата и время отправки'),
        ),
    ]
