# Generated by Django 4.1.2 on 2022-11-15 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_sender', '0008_remove_operator_code_alter_message_send_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_dt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 14, 56, 12, 797424, tzinfo=datetime.timezone.utc), verbose_name='Дата и время отправки'),
        ),
    ]
