# Generated by Django 4.1.2 on 2022-11-15 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_sender', '0009_alter_message_send_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='filtr',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='tags',
            field=models.ManyToManyField(blank=True, to='sms_sender.tag'),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_dt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 15, 20, 28, 590764, tzinfo=datetime.timezone.utc), verbose_name='Дата и время отправки'),
        ),
    ]
